#!/usr/bin/env python2.7

import json
import lxml.html
import mechanize
import packaging.version
import sys

br = mechanize.Browser()
br.set_handle_equiv(True)
br.set_handle_gzip(True)
br.set_handle_redirect(True)
br.set_handle_referer(True)
br.set_handle_robots(False)
br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(), max_time = 1)
br.addheaders = [('User-agent', 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.64 Safari/537.31 AlexaToolbar/alxg-3.1')]

response = br.open(sys.argv[1])
page = response.read()
page = lxml.html.fromstring(page)

links = [link.text[:-1] for link in page.cssselect('html > body > table > tr > td > a') if link.text[-1] == '/']
links = sorted(links, key = packaging.version.LegacyVersion, reverse = True)
print(links[0])

